# 服务端口配置
server:
  servlet:
    context-path: /

spring:
  # 当前使用的profile
  profiles:
    active: dev
# springmvc jsp目录配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # http 编码配置
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

# Shiro
shiro:
  uid:
    cookie:
      name: uid
      # 默认uid cookie 浏览器关闭后销毁
      maxAge: -1
    rememeberMe:
      cookie:
        name: rememberMe
        #默认 rememberMe cookie 60 * 60 * 24 * 7 （7天）
        maxAge: 604800
  active:
    session:
      cacheName: shiro-activeSessionCache